from .cheaplas import CheapLAS
from .hedged import *
from .jiq import JIQ
from .jsq import JSQ
from .multi import MultiDispatcher
from .rand import Rand
from .roundroubin import RoundRobin
from .sharedrr import SharedRoundRobin
from .silly import Silly
